// Generated by .NET Reflector from D:\桌面\新建文件夹\10.EQPIO_release_v2.17.07.12\bin\EQPIO.EIPDriver.dll
namespace EQPIO.EIPDriver.Compiler.Resources
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [DebuggerNonUserCode, GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), CompilerGenerated]
    internal class Description
    {
        private static CultureInfo resourceCulture;
        private static System.Resources.ResourceManager resourceMan;

        internal Description()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string ErrorActionFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorActionFormat", resourceCulture);
            }
        }

        internal static string ErrorActionNull
        {
            get
            {
                return ResourceManager.GetString("ErrorActionNull", resourceCulture);
            }
        }

        internal static string ErrorDeviceCodeFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorDeviceCodeFormat", resourceCulture);
            }
        }

        internal static string ErrorDeviceCodeNull
        {
            get
            {
                return ResourceManager.GetString("ErrorDeviceCodeNull", resourceCulture);
            }
        }

        internal static string ErrorEmpty
        {
            get
            {
                return ResourceManager.GetString("ErrorEmpty", resourceCulture);
            }
        }

        internal static string ErrorFormatA
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatA", resourceCulture);
            }
        }

        internal static string ErrorFormatB
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatB", resourceCulture);
            }
        }

        internal static string ErrorFormatBit
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatBit", resourceCulture);
            }
        }

        internal static string ErrorFormatH
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatH", resourceCulture);
            }
        }

        internal static string ErrorFormatI
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatI", resourceCulture);
            }
        }

        internal static string ErrorFormatSI
        {
            get
            {
                return ResourceManager.GetString("ErrorFormatSI", resourceCulture);
            }
        }

        internal static string ErrorHeadDeviceDecFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorHeadDeviceDecFormat", resourceCulture);
            }
        }

        internal static string ErrorHeadDeviceHexFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorHeadDeviceHexFormat", resourceCulture);
            }
        }

        internal static string ErrorHeadDeviceNull
        {
            get
            {
                return ResourceManager.GetString("ErrorHeadDeviceNull", resourceCulture);
            }
        }

        internal static string ErrorIntervalFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorIntervalFormat", resourceCulture);
            }
        }

        internal static string ErrorKeyInvalid
        {
            get
            {
                return ResourceManager.GetString("ErrorKeyInvalid", resourceCulture);
            }
        }

        internal static string ErrorKeyNull
        {
            get
            {
                return ResourceManager.GetString("ErrorKeyNull", resourceCulture);
            }
        }

        internal static string ErrorKeyUnique
        {
            get
            {
                return ResourceManager.GetString("ErrorKeyUnique", resourceCulture);
            }
        }

        internal static string ErrorLogModeFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorLogModeFormat", resourceCulture);
            }
        }

        internal static string ErrorOffsetBitFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorOffsetBitFormat", resourceCulture);
            }
        }

        internal static string ErrorOffsetFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorOffsetFormat", resourceCulture);
            }
        }

        internal static string ErrorOffsetNull
        {
            get
            {
                return ResourceManager.GetString("ErrorOffsetNull", resourceCulture);
            }
        }

        internal static string ErrorOutOfBounds
        {
            get
            {
                return ResourceManager.GetString("ErrorOutOfBounds", resourceCulture);
            }
        }

        internal static string ErrorPointBitFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorPointBitFormat", resourceCulture);
            }
        }

        internal static string ErrorPointFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorPointFormat", resourceCulture);
            }
        }

        internal static string ErrorPointNull
        {
            get
            {
                return ResourceManager.GetString("ErrorPointNull", resourceCulture);
            }
        }

        internal static string ErrorRepresentationBit
        {
            get
            {
                return ResourceManager.GetString("ErrorRepresentationBit", resourceCulture);
            }
        }

        internal static string ErrorRepresentationFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorRepresentationFormat", resourceCulture);
            }
        }

        internal static string ErrorRepresentationNull
        {
            get
            {
                return ResourceManager.GetString("ErrorRepresentationNull", resourceCulture);
            }
        }

        internal static string ErrorSizeA
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeA", resourceCulture);
            }
        }

        internal static string ErrorSizeB
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeB", resourceCulture);
            }
        }

        internal static string ErrorSizeBit
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeBit", resourceCulture);
            }
        }

        internal static string ErrorSizeH
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeH", resourceCulture);
            }
        }

        internal static string ErrorSizeI
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeI", resourceCulture);
            }
        }

        internal static string ErrorSizeSI
        {
            get
            {
                return ResourceManager.GetString("ErrorSizeSI", resourceCulture);
            }
        }

        internal static string ErrorStartUpFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorStartUpFormat", resourceCulture);
            }
        }

        internal static string ErrorTriggerFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorTriggerFormat", resourceCulture);
            }
        }

        internal static string ErrorUndefine
        {
            get
            {
                return ResourceManager.GetString("ErrorUndefine", resourceCulture);
            }
        }

        internal static string ErrorUnique
        {
            get
            {
                return ResourceManager.GetString("ErrorUnique", resourceCulture);
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    System.Resources.ResourceManager manager = new System.Resources.ResourceManager("EQPIO.EIPDriver.Compiler.Resources.Description", typeof(Description).Assembly);
                    resourceMan = manager;
                }
                return resourceMan;
            }
        }

        internal static string WarnEmpty
        {
            get
            {
                return ResourceManager.GetString("WarnEmpty", resourceCulture);
            }
        }
    }
}
