//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQPIO.Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQPIO.Controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;EQPIOConfig&gt;
        ///	&lt;Driver name = &quot;MQ&quot;&gt;
        ///		&lt;ConnectionInfo name = &quot;MQ&quot; path = &quot;../IOCon/Config/MQ/EQInterface.xml&quot; use = &quot;false&quot;/&gt;
        ///	&lt;/Driver&gt;
        ///	&lt;Driver name = &quot;MelsecBoard&quot;&gt;
        ///		&lt;ConnectionInfo name = &quot;Board&quot; path = &quot;../IOCon/Config/MelsecBoard/MNetConfig.xml&quot; use = &quot;false&quot;/&gt;
        ///	&lt;/Driver&gt;
        ///	&lt;Driver name = &quot;MelsecEthernet&quot;&gt;
        ///		&lt;ConnectionInfo name = &quot;Ethernet&quot; path = &quot;../IOCon/Config/MelsecEthernet/MNetConfig.xml&quot; use = &quot;true&quot;/&gt;		
        ///	&lt;/Driver&gt;
        ///	&lt;Driver name = &quot;EIP&quot;&gt;
        ///		&lt;Co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EQPConfig {
            get {
                return ResourceManager.GetString("EQPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Configuration&gt;
        ///  &lt;ConnectionInfo LocalName=&quot;L2&quot; PLCMapFile=&quot;..\IOCon\Config\MelsecEthernet\PLCMap.xml&quot; IpAddress=&quot;192.168.51.9&quot; MelsecPort=&quot;7006,7007&quot; FixedBufferPort=&quot;7002&quot; IsMelsecEnabled=&quot;true&quot; IsFixedBufferEnabled=&quot;false&quot; CodeType=&quot;ASCII&quot; NetworkNo=&quot;99&quot; PCNo=&quot;1&quot; CPUType = &quot;Q&quot; DirectAccess=&quot;false&quot;/&gt;
        ///  &lt;/Configuration&gt; 的本地化字符串。
        /// </summary>
        internal static string MNetConfig {
            get {
                return ResourceManager.GetString("MNetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;PLCDriver&gt;
        ///&lt;ItemGroupCollection&gt;
        ///    &lt;ItemGroup Name=&quot;Port#1PortStatusBlock&quot;&gt;
        ///      &lt;Item Name=&quot;PortStatus&quot; Offset=&quot;0&quot; Points=&quot;1&quot; Representation=&quot;I&quot; /&gt;
        ///      &lt;Item Name=&quot;CassetteStatus&quot; Offset=&quot;1&quot; Points=&quot;1&quot; Representation=&quot;I&quot; /&gt;
        ///      &lt;Item Name=&quot;CassetteSequenceNo&quot; Offset=&quot;2&quot; Points=&quot;1&quot; Representation=&quot;I&quot; /&gt;
        ///      &lt;Item Name=&quot;CassetteID&quot; Offset=&quot;3&quot; Points=&quot;13&quot; Representation=&quot;A&quot; /&gt;
        ///      &lt;Item Name=&quot;JobCountinCassette&quot; Offset=&quot;16&quot; Points=&quot;1&quot; Representation=&quot;I&quot; /&gt;
        ///      &lt;Item Name=&quot;CompletedCasset [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PLCMap {
            get {
                return ResourceManager.GetString("PLCMap", resourceCulture);
            }
        }
    }
}
